version: '3'
services:
  ctf_challenge:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./flags:/var/www/html/flags
      - ./web_app:/var/www/html/juice-shop
    environment:
      - MYSQL_ROOT_PASSWORD=root
